[variables][variables]

NPM_CONFIG_PRODUCTION = "false"NPM_CONFIG_PRODUCTION = "false"



[phases.setup][phases.install]

cmds = ["corepack enable", "corepack prepare pnpm@8.15.5 --activate"]cmds = [

  "npm install -g pnpm@8.15.5",

[phases.install]   "pnpm install --no-frozen-lockfile"

cmds = ["pnpm install --no-frozen-lockfile"]]



[phases.build][phases.build]

cmds = ["pnpm run build"]cmds = ["pnpm run build"]



[start][start]

cmd = "pnpm run start"cmd = "pnpm run preview"