[variables]
NPM_CONFIG_PRODUCTION = "false"

[phases.install]
cmds = [
  "npm install -g pnpm@8.15.5",
  "pnpm install --no-frozen-lockfile"
]

[phases.build]
cmds = ["pnpm run build"]

[start]
cmd = "pnpm run preview"